/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e4e2e1",
        "secondary-container": "#c7e9ed",
        "on-surface": "#171c22",
        "surface-container": "#eaeef7",
        "tertiary-container": "#989797",
        "on-primary-container": "#003639",
        "primary-container": "#51a4aa",
        "inverse-on-surface": "#edf1fa",
        error: "#ba1a1a",
        "surface-dim": "#d6dae3",
        background: "#f8f9ff",
        "on-background": "#171c22",
        "on-surface-variant": "#3e4949",
        "surface-container-highest": "#dee3eb",
        "on-tertiary-fixed-variant": "#474747",
        "surface-variant": "#dee3eb",
        surface: "#f8f9ff",
        "surface-tint": "#00696f",
        "on-secondary-fixed": "#001f23",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c6",
        tertiary: "#5f5e5e",
        "secondary-fixed-dim": "#abccd1",
        "surface-container-lowest": "#ffffff",
        primary: "#00696f",
        "on-primary-fixed": "#002022",
        "on-secondary-container": "#4a6a6e",
        "inverse-primary": "#82d4da",
        "on-primary-fixed-variant": "#004f53",
        "secondary-fixed": "#c7e9ed",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#2d4c50",
        "on-tertiary-container": "#303030",
        "on-error": "#ffffff",
        "inverse-surface": "#2c3137",
        "primary-fixed-dim": "#82d4da",
        secondary: "#446368",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-container-low": "#f0f4fd",
        "on-tertiary": "#ffffff",
        "outline-variant": "#bec9c9",
        outline: "#6e797a",
        "surface-container-high": "#e4e8f1",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9ff",
        "on-error-container": "#93000a",
        "primary-fixed": "#9ef0f6",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
